baseURL = "practical-lewin-20dbe8.netlify.com/"
languageCode = "en-us"
title = "Veronica Liu"
theme = "hugo-lodi-theme"

[params]
    theme_color = "#AA0055"
    description = "Portfolio of Veronica Liu, Animator and Lighting Artist"
    description_photo = "linkedin_veronica.jpeg"
    favicon = "favicon.ico"
    logo = "favicon.ico"
    email = "verliu21@gmail.com"
    linkedin = "https://www.linkedin.com/in/veronica-liu/"
    github = "verliu21"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "linkedin_veronica.jpeg"
    subtitle = "Hi! I'm Veronica."
    hero_right = ["**Currently a Render Wrangler at Rooster Teeth. Currently an Arts and Technology major (Animation Track) at UT Dallas.**", "I founded [User Experience Society](https://www.facebook.com/UXSoc/), the first student UX organization in the Philippines. For two years, we've had 20+ events with 30+ speakers for over 300 members and 500+ attendees. We've expanded to [California](https://www.facebook.com/profile.php?id=245708449193012) this year.", "I do a bit of writing as well. [Here's an article with a total of 21,000+ views to InVision & Medium](http://blog.invisionapp.com/ux-internship-wisdom/) talking about 50 things I learned spending 3 years as a UX intern.", "I help cultivate the design community in Manila too. I'm the youngest core member of [UX Philippines](https://www.facebook.com/groups/uxphilippines/) and I moderated a panel with some cool people for the [UXPH 2017 Conference](https://www.uxphilippines.com).", "I'm finishing my Bachelor's degree in Management Information Systems at the Ateneo de Manila University, expecting to graduate in 2018."]
    resume = "LiuResume.pdf"

[params.process]
    enable = true
    title = "My Specialties"
    subtitle = "Subtitle here"

[params.case_studies]
    enable = true
    title = "Portfolio"
    subtitle = "Selected Works"

[params.footer]
    enable = true
