baseURL = "/"
languageCode = "en-us"
title = "Veronica Liu"
theme = "hugo-lodi-theme"

[params]
    theme_color = "#AA0055"
    description = "Portfolio of Veronica Liu, Animator and Lighting Artist"
    description_photo = "linkedin_veronica.jpeg"
    favicon = "favicon.ico"
    logo = "favicon.ico"
    email = "verliu21@gmail.com"
    linkedin = "https://www.linkedin.com/in/veronica-liu/"
    github = "verliu21"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "linkedin_veronica.jpeg"
    subtitle = "Hi! I'm Veronica Liu."
    hero_right = ["**Currently looking for lighting/compositing or animation roles. Formerly a Render Wrangler at Rooster Teeth.**", "I’m finishing my Bachelor’s degree in Arts and Technology on the animation track at the [University of Texas at Dallas](https://atec.utdallas.edu/), and expect to graduate in **Spring 2020**.", "I worked on a motion capture short called [“Taking the Plunge”](https://youtu.be/MU-F71tI4TE) with 12 other students and was responsible for preproduction work and the rendering process.", "I reestablished the [Animation Guild at UT Dallas](https://animationutd.com/), turning it from a fangroup club with 8 members into a preprofessional animation group, and helped out in multiple roles in the organization. While I was an officer, we’ve run 20+ events, maintained over 100 members each semester and brought in 22 industry speakers for events on campus.", "I’ve had the opportunity to be a [SIGGRAPH](https://www.siggraph.org/) SV for SIGGRAPH 2017, 2018, and am involved with [ABOSG](https://www.abunchofshortguys.org/), Dallas’s local animation group."]
    resume = "LiuResume.pdf"

[params.process]
    enable = true
    title = "My Specialties"
    subtitle = ""

[params.case_studies]
    enable = true
    title = "Portfolio"
    subtitle = "Selected Works"

[params.footer]
    enable = true
